restaurant_name = "EG's Garden Grill"
happy_hour_special = "Buy One Get One Free Appetizers"
ladies_night_special = "Ladies Well Drinks $1 Each"
total_number_servers = 9
total_number_cooks = 5
cost_beer_order = 872.63
open_wednesdays = false
open_for_breakfast = true
has_kids_menu = true
is_wheelchair_accessible = true
