restaurant_name = "EG's Garden Grill"
happy_hour_special = "Buy One Get One Free Appetizers"
ladies_night_special = "Ladies Well Drinks $1 Each"
total_number_servers = 6
total_number_cooks = 3
cost_beer_order = 872.63
open_wednesdays = false
open_for_breakfast = true
has_kids_menu = true
is_wheelchair_accessible = true
server_first_names = ["Julie", "John", "Matthew", "Christopher", "Cindy", "Alexandra"]
cook_first_names = ["Jake", "Max", "Jennifer"]
open_days = ["Thursday", "Friday", "Saturday", "Sunday", "Monday", "Tuesday"]
